'use client'
import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import SideBar from '@/components/SideBar'
import { IndexProvider } from './context/selectedIndex'
import { usePathname } from 'next/navigation'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Oğuz Adıgüzel',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const path = usePathname()
  console.log('path',path);
  
  return (
    <IndexProvider>
    <html lang="en">
      <body className='bg-black text-white'>
        <div className='container mx-auto h-screen'>
          <Header />
          <div className='w-full flex flex-col lg:flex-row py-5'>
            <div className='w-full lg:w-1/6 lg:h-screen'>
              <SideBar menu={false} />
            </div>
            <div className='w-full lg:w-5/6'>
              {children}
            </div>
          </div>
        </div>

      </body>
    </html>
    </IndexProvider>
  )
}
